{{- if not .Values.secretKeyRefNameOverride }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  ClientID: "{{ .Values.azureClientID | b64enc }}"
  ClientSecret: "{{ .Values.azureClientSecret | b64enc }}"
  ResourceGroup: "{{ .Values.azureResourceGroup | b64enc }}"
  SubscriptionID: "{{ .Values.azureSubscriptionID | b64enc }}"
  TenantID: "{{ .Values.azureTenantID | b64enc }}"
  VMType: "{{ .Values.azureVMType | b64enc }}"
  UserAssignedIdentityID: "{{ .Values.azureUserAssignedIdentityID | b64enc }}"
{{- end }}
